properties:
  NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET  
  image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  ubbAgentImage:
    type: string
    default: gcr.io/neo4j-k8s-marketplace-public/ubbagent:neo4j
    x-google-marketplace:
      type: IMAGE
  coreServers:
    title: Server replicas to use
    type: int
    default: 3
    minimum: 3
    maximum: 9
  readReplicaServers:
    title: Read Replicas
    type: int
    default: 0
    minimum: 0
    maximum: 9
  authEnabled:
    title: Enable Authorization
    type: string
    default: "true"
    enum:
    - "true"
    - "false"
  cpu:
    title: CPU units per node
    type: string
    default: "100m"
  mem:
    title: Memory per node
    type: string
    default: "512M"
  volumeSize:
    title: Disk allocation to core nodes
    type: string
    default: "2Gi"
  volumeStorageClass:
    title: Storage class for nodes, pd-ssd for SSD storage recommended.
    type: string
    default: "-"
    enum:
    - "-"
required:
- NAME
- NAMESPACE
- image
- reportingSecret
