properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET  
  image:
    type: string
    default: gcr.io/neo4j-k8s-marketplace-public/neo4j:3.3.5-enterprise
    x-google-marketplace:
      type: IMAGE
  ubbAgentImage:
    type: string
    default: gcr.io/neo4j-k8s-marketplace-public/ubbagent:neo4j
    x-google-marketplace:
      type: IMAGE
  coreServers:
    title: Server replicas to use
    type: int
    default: 3
    minimum: 3
  readReplicaServers:
    title: Read Replicas
    type: int
    default: 0
    minimum: 0
  authEnabled:
    title: Enable Authorization
    type: string
    default: true
  
required:
- APP_INSTANCE_NAME
- NAMESPACE
- image
- reportingSecret
- coreServers
