apiVersion: batch/v1
kind: Job
metadata:
  name: "neo4j-tester"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  template:
    spec:
      containers:
      - name: tester
        image: "{{ .Values.tester.image }}"
        env:
        - name: EXITCODE
          value: "{{ .Values.tester.exitcode }}"
        - name: DURATION
          value: "{{ .Values.tester.duration }}"
      restartPolicy: Never
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  initContainers:
  - name: test-framework
    image: "gcr.io/neo4j-k8s-marketplace-public/dduportal/bats:0.4.0"
    command: ["bash", "-c", "set -ex\ncp -R /usr/local/libexec/ /tools/bats/"]
    volumeMounts:
      - mountPath: "/tools"
        name: tools
  volumes:
  - name: tests
    configMap:
      name: {{ template "neo4j.fullname" . }}-tests
  - name: tools
    emptyDir: {}      
  backoffLimit: 0
