properties:
  name:
    type: string
    x-google-marketplace:
     type: INSTANCE_NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  neo4jImage:
    type: string
    default: gcr.io/neo4j-k8s-marketplace-public/neo4j:3.3.5-enterprise
    x-google-marketplace:
      type: IMAGE
  ubbAgentImage:
    type: string
    default: gcr.io/neo4j-k8s-marketplace-public/ubbagent:neo4j
    x-google-marketplace:
      type: IMAGE
  serverReplicas:
    title: Server replicas
    type: int
    default: 1
    minimum: 1
  blogTitle:
    title: Blog title
    description: WordPress requires a blog title for setup. This can be changed later.
    type: string
    maxLength: 128
required:
- name
- namespace
- reportingSecret
- wordpressImage
- ubbAgentImage
- serveReplicas
- blogTitle